// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Mintegral",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Mintegral", targets: ["AATKit-Mintegral"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Mintegral",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATMintegralAdapter",
                    "AATMTGSDKInterstitialVideo",
                    "AATMTGSDKBanner",
                    "AATMTGSDKBidding",
                    "AATMTGSDKReward",
                    "AATMTGSDKNativeAdvanced",
                    "AATMTGSDKSplash",
                    "AATMTGSDKNewInterstitial",
                    "AATMTGSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Mintegral"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATMintegralAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATMintegralAdapter.zip",
            checksum: "3ac6f9e9d3dfda61440577bfcbf1eb18dc5ed6bd84cd5e3ecf235982e213052d"
        ),
        .binaryTarget(
            name: "AATMTGSDKInterstitialVideo",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDKInterstitialVideo.zip",
            checksum: "b340e2631cd819c87fc434b7b1db2e6d4460a50e8c68b82d3b4dce986e22b142"
        ),
        .binaryTarget(
            name: "AATMTGSDKBanner",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDKBanner.zip",
            checksum: "9900f374b7459720edac023782554077a6f6481199a9b7abccd11f47655cbcc1"
        ),
        .binaryTarget(
            name: "AATMTGSDKBidding",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDKBidding.zip",
            checksum: "b073b334553e404265ab2e292c2a865533e3efb790cda0bede3792d4768f643c"
        ),
        .binaryTarget(
            name: "AATMTGSDKReward",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDKReward.zip",
            checksum: "8cc0059eacefc1b2824c4f815c93bb548b9aa84607db6810adfb4c8703047d07"
        ),
        .binaryTarget(
            name: "AATMTGSDKNativeAdvanced",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDKNativeAdvanced.zip",
            checksum: "f68fd8ef7e192c08696f8e835c46e5395fcf3c1946386160fb22826e072c99cd"
        ),
        .binaryTarget(
            name: "AATMTGSDKSplash",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDKSplash.zip",
            checksum: "1a9e235870ddf9d00569433f2ab7e3ef9074d3af8ef3e3204d97e66989652865"
        ),
        .binaryTarget(
            name: "AATMTGSDKNewInterstitial",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDKNewInterstitial.zip",
            checksum: "fee99a0c1235fdf2fe84322ef49f2499251f314889eed66d5d8d104aaa3c68b8"
        ),
        .binaryTarget(
            name: "AATMTGSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/MTGSDK.zip",
            checksum: "24134f9e90235c5fff0873811318a43c277b03dbd9d01fec3ef7c3a1f72db94f"
        ),
    ]
)
