// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Mintegral",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Mintegral", targets: ["AATKit-Mintegral"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Mintegral",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATMintegralAdapter",
                    "AATMTGSDKInterstitialVideo",
                    "AATMTGSDKBanner",
                    "AATMTGSDKBidding",
                    "AATMTGSDKReward",
                    "AATMTGSDKNativeAdvanced",
                    "AATMTGSDKSplash",
                    "AATMTGSDKNewInterstitial",
                    "AATMTGSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Mintegral"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATMintegralAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AATMintegralAdapter.zip",
            checksum: "fb1af4a7f0686c13fb7d335114fb6b3e18c426c6f5bdf969e76081b0e0fb0bf6"
        ),
        .binaryTarget(
            name: "AATMTGSDKInterstitialVideo",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDKInterstitialVideo.zip",
            checksum: "64fafb6cf9fee20c982e0308654ae796153d8ed47d7de10888cd3b33f1293e82"
        ),
        .binaryTarget(
            name: "AATMTGSDKBanner",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDKBanner.zip",
            checksum: "831a71bc95e90e090a3798a93d4ee6c10f94721b0abc19348798153cd32c9d95"
        ),
        .binaryTarget(
            name: "AATMTGSDKBidding",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDKBidding.zip",
            checksum: "113106d0c9ffcf7bec5e917be3d50c4bf427b731151829c0a2b70789208d4017"
        ),
        .binaryTarget(
            name: "AATMTGSDKReward",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDKReward.zip",
            checksum: "b0a37a796cc06c6e2042a20be8e2c6b79c5cfbe983aa24bb5a32e51107cf9c74"
        ),
        .binaryTarget(
            name: "AATMTGSDKNativeAdvanced",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDKNativeAdvanced.zip",
            checksum: "26419d86399e88f98bf464474000bf606253a151521fe7773248f396ed4d55f6"
        ),
        .binaryTarget(
            name: "AATMTGSDKSplash",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDKSplash.zip",
            checksum: "91f8227ada2f4cfc7e5d45174d52d8f9f460357758e695c8462f88c4dbb2d4ff"
        ),
        .binaryTarget(
            name: "AATMTGSDKNewInterstitial",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDKNewInterstitial.zip",
            checksum: "ff2dc143d00e13f4e7b5a7af604985b0d03470e3ff36c00187ddb3a2ad6e2e8e"
        ),
        .binaryTarget(
            name: "AATMTGSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MTGSDK.zip",
            checksum: "1755317f701c8872a1751978a3e30af6a68fbe4cefbdf17ce2198e8cba2e54f5"
        ),
    ]
)
