// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Mintegral",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Mintegral", targets: ["AATKit-Mintegral"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Mintegral",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATMintegralAdapter",
                    "AATMTGSDKInterstitialVideo",
                    "AATMTGSDKBanner",
                    "AATMTGSDKBidding",
                    "AATMTGSDKReward",
                    "AATMTGSDKNativeAdvanced",
                    "AATMTGSDKSplash",
                    "AATMTGSDKNewInterstitial",
                    "AATMTGSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Mintegral"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATMintegralAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATMintegralAdapter.zip",
            checksum: "e30caa2836a9a272208947164f96eed0d30db5cf44eca8250db3a7e15b66344c"
        ),
        .binaryTarget(
            name: "AATMTGSDKInterstitialVideo",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDKInterstitialVideo.zip",
            checksum: "29819d18210703ace2d96aa0bcf0803bb33f4db859f274c671546eed0cd12774"
        ),
        .binaryTarget(
            name: "AATMTGSDKBanner",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDKBanner.zip",
            checksum: "fc41e5cedb41fba6698afa74dcf91ecc1d4ccaba9d72bda1594efbfb1c0e5510"
        ),
        .binaryTarget(
            name: "AATMTGSDKBidding",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDKBidding.zip",
            checksum: "8c977ed2a6e08479f38646dfd76c0b8ae7240f686de2f514dff8f93f3dac6cb3"
        ),
        .binaryTarget(
            name: "AATMTGSDKReward",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDKReward.zip",
            checksum: "df2464d02e55f34ad3c0825cf2c536d5c369730715e7896411826bdd69e35bd4"
        ),
        .binaryTarget(
            name: "AATMTGSDKNativeAdvanced",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDKNativeAdvanced.zip",
            checksum: "9594934e4099cc08e8097a9ce862cdf185a8274d1b11df0c3dce13a81a9dfdfb"
        ),
        .binaryTarget(
            name: "AATMTGSDKSplash",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDKSplash.zip",
            checksum: "1d7c0203dc36f89d6ac9c4cf36218519652fae290ed9cb70b9f3d9c45b221017"
        ),
        .binaryTarget(
            name: "AATMTGSDKNewInterstitial",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDKNewInterstitial.zip",
            checksum: "ed5e7acdd3ff844be5638c300bca5f0d929b163c729e188c5ef26825d037c4e4"
        ),
        .binaryTarget(
            name: "AATMTGSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MTGSDK.zip",
            checksum: "a09873d8d929fb347eba3e93f4404190f2a0ae06c6b9b1ea71795e9560eaef65"
        ),
    ]
)
